# -*- coding: utf-8 -*-
"""Assignment 02_20301443_Hamim_Ibna_Nasim__11_CSE111.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yfqGhKBr9w0lnx-KYe2AQZC1yeqiacc6

# Function
## Task 1
"""

def fractionReturn(value_one,value_two):
    if value_one==0 or value_two== 0 :
        return 0
    else:
        divi_sion = (value_one/value_two)
        floor_division = (value_one//value_two)
        fraction_part =division-floor_division
        return fraction_part
    
final_result=fractionReturn(11,3)
print(final_result)

"""## task 2"""

def BMI(height,weight):
    
    actual_height = (height/100)
    user_bmi = weight/((actual_height)**2)
    user_message=""
    
    if user_bmi < 18.5:
        user_message="Underweight"
    elif user_bmi>=18.5 and user_bmi<=24.9:
        user_message="Normal"
    elif user_bmi>=25 and user_bmi<=30:
        user_message="Overweight"
    elif user_bmi>30:
        user_message="Obese"
        
    print("Your score is {}. You are {}".format(round(user_bmi,1),user_message))
    
BMI(152,48)

"""## Task 3"""

def m(m1,m2,v):
    s=0
    for i in range (m1,m2):
        if i % v==0:
            s+= i
    return s
        
print( m(3,16,3))

"""## Task 4"""

def priceCalculator(delivery_burger,delivery_place="Mohakhali"):
    total_price = 0
    burger_price = 0
    
    if delivery_burger =="BBQ Chicken Cheese Burger":
        burger_price = 250
    elif delivery_burger =="Beef Burger":
        burger_price = 170
    elif delivery_burger =="Naga Drums":
        burger_price = 200
        
    total_tax=(burger_price*.08)
    total_burger_price=burger_price + total_tax
    
    if delivery_place=="Mohakhali":
        total_price = total_burger_price + 40
    else:
        total_price = total_burger_price + 60
    return total_price

final_price= priceCalculator("Beef Burger","Dhanmondi")
    
print(final_price)

"""## Task 5"""

def replace_domain(email_address,new_domain,old_domain="kaaj.com"):
    if new_domain in email_address:
        function_output = ("Unchanged: "+email_address)
    else:
        name_part=(email_address).split(old_domain)
        function_output =("Changed: "+name_part[0]+new_domain)
    print(function_output)

final_result=replace_domain("alice@yahooo.xyz","sheba.xyz","yahoo.xyz")

"""## Task 6"""

def vx(a):
    v1=""
    c=0
    for i in a:
        if i in "aeiou":
            v1 += (i+",")
            c +=1
    if v1=="":
        print("No vowels in the name")
    else:
        print((v1.strip(","),c))
        
vx("Hellow")

"""## Task 7"""

def palindromeChecker(given_input):
    actual_word=""
    for char in given_input:
        if char!=" ":
            actual_word +=char
            
    first_part = actual_word
    second_part= actual_word[len(actual_word)::-1]
    
    if  first_part == second_part:
        print("Palindrome")
    else:
        print("Not a palindrome")
        
palindromeChecker("M A D A M")

"""## Task 8"""

#considered day=31

def daysConverter(number_of_days):
    years= (number_of_days)// 365
    months =(number_of_days % 365)//31
    days = (number_of_days % 365 % 31)
    print("{} years, {} months and {} days".format(years,months,days))
    
daysConverter(4000)

"""## Task 9"""

ui=input()
def s(ui1):
    ui = ui1.split("!")
    a=[]
    n=[]
    for i in ui:
        a +=i.split(".")
    for i in a:
        n+=i.split("?")
    cc=ic= ""
    for i in n:
        if i != "":
            ic= (i.strip())
            cc  = ic[0].upper()+ ic[1:]
        r=""
        for i in (cc.split()):
            if i =="i":
                r += "I"+ " "
            else:
                r += i+" "
        ui1=ui1.replace(ic,r.strip())
    return (ui1)
print(s(ui))



