# -*- coding: utf-8 -*-
"""Assignment 03_20301443_HamimIbnaNasim_11_CSE111.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18HAyaXjyC4Nrto92n9gmG8DQAYJ4FzCM

# OOP

## Task 1
"""

class DataType:
    def __init__(self,name,value):
        self.name= name
        self.value=value


data_type1 = DataType("Integer", 1234)
print(data_type1.name)
print(data_type1.value)
print('=====================')
data_type2 = DataType("String", "Hello")
print(data_type2.name)
print(data_type2.value)
print('=====================')
data_type3 = DataType("Float", 4.0)
print(data_type3.name)
print(data_type3.value)

"""## Task 2"""

class Flower:
    def __init__(self):
        self.name=""
        self.color=""
        self.num_of_petal=""
        

flower1 = Flower()
flower1.name="Rose"
flower1.color="Red"
flower1.num_of_petal=6
print("Name of this flower:", flower1.name)
print("Color of this flower:",flower1.color)
print("Number of petal:",flower1.num_of_petal)
print("=====================")
flower2 = Flower()
flower2.name="Orchid"
flower2.color="Purple"
flower2.num_of_petal=4
print("Name of this flower:",flower2.name)
print("Color of this flower:",flower2.color)
print ("Number of petal:",flower2. num_of_petal)

"""## Task 3"""

class Wadiya():
    def __init__(self):
        self.name = 'Aladeen'
        self.designation = 'President Prime Minister Admiral General'
        self.num_of_wife = 100
        self.dictator = True
        
Wadiya1= Wadiya()
print("Part 1:")
print("Name of President:", Wadiya1.name)
print("Designation:", Wadiya1.designation)
print("Number of wife:", Wadiya1.num_of_wife)
print("Is he/she a dictator:", Wadiya1.dictator)

Wadiya1.name="Donald Trump"
Wadiya1.designation="President"
Wadiya1.num_of_wife= 1
Wadiya1.dictator =False
print("Part 2:")
print("Name of President:", Wadiya1.name)
print("Designation:", Wadiya1.designation)
print("Number of wife:", Wadiya1.num_of_wife)
print("Is he/she a dictator:", Wadiya1.dictator)

"""## Task 4"""

class Joker:
    def __init__(self,name,power,is_he_psycho):
        self.name=name
        self.power=power
        self.is_he_psycho=is_he_psycho

j1 = Joker('Heath Ledger', 'Mind Game', False)
print(j1.name)
print(j1.power)
print(j1.is_he_psycho)
print("=====================")
j2 = Joker('Joaquin Phoenix', 'Laughing out Loud', True)
print(j2.name)
print(j2.power)
print(j2.is_he_psycho)
print("=====================")
if j1 == j2:
    print('same')
else:
    print('different')
j2.name = 'Heath Ledger'
if j1.name == j2.name:
    print('same')
else:
    print('different')

"""## Task 5"""

class Pokemon:
    def __init__(self,pokemon1_name,pokemon2_name,pokemon1_power,pokemon2_power,damage_rate):
        self.pokemon1_name = pokemon1_name
        self.pokemon2_name = pokemon2_name
        self.pokemon1_power= pokemon1_power
        self.pokemon2_power= pokemon2_power
        self.damage_rate   = damage_rate
        
team_pika = Pokemon('pikachu', 'charmander', 90, 60, 10)
print('=======Team 1=======')
print('Pokemon 1:',team_pika.pokemon1_name,team_pika.pokemon1_power)
print('Pokemon 2:',team_pika.pokemon2_name,team_pika.pokemon2_power)
pika_combined_power = (team_pika.pokemon1_power + team_pika.pokemon2_power) * team_pika.damage_rate
print('Combined Power:', pika_combined_power)

team_pika_two = Pokemon('bulbasaur', 'squirtle', 70, 80, 9)
print('=======Team 2=======')
print('Pokemon 1:',team_pika_two.pokemon1_name,team_pika_two.pokemon1_power)
print('Pokemon 2:',team_pika_two.pokemon2_name,team_pika_two.pokemon2_power)
pika_combined_power = (team_pika_two.pokemon1_power + team_pika_two.pokemon2_power) * team_pika_two.damage_rate
print('Combined Power:', pika_combined_power)

"""## Task 6"""

class Player:
    def __init__(self):
        self.name=""
        self.jersy_number=""
        self.position=""
        
player1 = Player()
player1.name = "Ronaldo"
player1.jersy_number = 9
player1.position = "Striker"
print("Name of the Player:", player1.name)
print("Jersey Number of player:", player1.jersy_number)
print("Position of player:", player1.position)
print("===========================")
player2 = Player()
player2.name = "Neuer"
player2.jersy_number = 1
player2.position = "Goal Keeper"
print("Name of the player:", player2.name)
print("Jersey Number of player:", player2.jersy_number)
print("Position of player:", player2.position)

"""## Task 7"""

class Country:
    def __init__(self):
        self.name="Bangladesh"
        self.continent="Asia"
        self.capital="Dhaka"
        self.fifa_ranking=187
        
country = Country()
print('Name:',country.name)
print('Continent:',country.continent)
print('Capital:',country.capital)
print('Fifa Ranking:',country.fifa_ranking)
print('===================')
country.name = "Belgium"
country.continent = "Europe"
country.capital = "Brussels"
country.fifa_ranking = 1
print('Name:',country.name)
print('Continent:',country.continent)
print('Capital:',country.capital)
print('Fifa Ranking:',country.fifa_ranking)

"""## Task 8"""

class DemonSlayer:
    def __init__(self,name,style,number_of_technique,kill):
        self.name=name
        self.style=style
        self.number_of_technique=number_of_technique
        self.kill=kill
        
tanjiro = DemonSlayer("Tanjiro", "Water Breathing", 10, 10)
print('Name:',tanjiro.name)
print('Fighting Style:',tanjiro.style)
print(f'Knows {tanjiro.number_of_technique} technique(s) and has killed {tanjiro.kill} demon(s)')
print('===================')

zenitsu = DemonSlayer("Zenitsu", "Thunder Breathing", 1, 4)
print('Name:',zenitsu.name)
print('Fighting Style:',zenitsu.style)
print(f'Knows {zenitsu.number_of_technique} technique(s) and has killed {zenitsu.kill} demon(s)')
print('===================')

inosuke = DemonSlayer("Inosuke", "Beast Breathing", 5, 7)
print('Name:',inosuke.name)
print('Fighting Style:',inosuke.style)
print(f'Knows {inosuke.number_of_technique} technique(s) and has killed {inosuke.kill} demon(s)')
print('===================')

print(f'{tanjiro.name}, {zenitsu.name}, {inosuke.name} knows total {tanjiro.number_of_technique + zenitsu.number_of_technique + inosuke.number_of_technique} techniques')
print(f'They have killed total {tanjiro.kill + zenitsu.kill + inosuke.kill} demons')